server:
  servlet:
    # 请求数据转码UTF8
    encoding:
      enabled: true
      charset: UTF-8
      force: true
logging:
  level:
    web: debug
    org:
      example:
        rabbitmq: debug

spring:
  rabbitmq:
    addresses: 127.0.0.1
    host: 5672
    username: guest
    password: guest
    virtual-host: /
    # 手动确认消息
    listener:
      simple:
        acknowledge-mode: manual
